### PR TITLE
Sort URLs by clicking a button

### PR DESCRIPTION
**Pull request by ashrafchowdury**
I create a project which makes **URLs sort** by clicking a button.

### CODE REVIEW

**Comment by surajondev** [comment]
The website looks awesome and does its job. But why have you put the code in the `JavaScript Meme Maker` directory?

**Comment by ashrafchowdury** [comment]
I saw the directory name. It was a mistake, and I changed the directory name perfectly. I hope all things are good now.

**Comment by ashrafchowdury** [comment]
> The website looks awesome and does its job. But why have you put the code in the `JavaScript Meme Maker` directory?

I think all issues are fixed now.

**Review by surajondev — APPROVED** [review]

**Comment by surajondev** [comment]
Thanks for the PR. The website looks dope and does the job. It has been merged.

I will be glad if you can leave a star on this repository.

**Pull request merged**
