### PR TITLE
Added JS DrumKit Project

### PR DESCRIPTION
**Pull request by Aryan-Bhatt-pro**
Have added the Javascript DrumKit Project. Request to please label it as hacktober-fest-accepted

### CODE REVIEW

**Comment by surajondev** [comment]
I can't see any code inside the submitted directory.

**Comment by Aryan-Bhatt-pro** [comment]
Oh sorry. Let me see whats the issue

**Comment by Aryan-Bhatt-pro** [comment]
Hi, sorry for the issue can you check now

**Comment by Aryan-Bhatt-pro** [comment]
Hi, @surajondev. Can you confirm whether the code is visible now?

**Review by surajondev — APPROVED** [review]

**Comment by surajondev** [comment]
Thanks for the PR. The website looks dope. It has been merged.

I will be glad if you can leave a star on this repository.

**Pull request merged**
